_content:
    value:
        general: '{''output_path'': ''./models/trained/'', ''model_name'': ''test_model_srv'', ''experiment_name'': ''quick_test_srv_experiment'', ''dataset'': ''../datasets/paper_quditkit'', ''njobs'': 16, ''device'': ''auto'', ''resume'': False, ''verbose'': True}'
        model: '{''type'': ''QC_Cond_UNet'', ''save_type'': ''pt'', ''params'': {''model_features'': [128, 128, 256], ''clr_dim'': 8, ''num_clrs'': 9, ''t_emb_size'': 256, ''cond_emb_size'': 512, ''num_heads'': [8, 8, 2], ''num_res_blocks'': [2, 2, 2], ''transformer_depths'': [1, 1, 1]}}'
        scheduler: '{''type'': ''DDIMScheduler'', ''params'': {''num_train_timesteps'': 1000, ''beta_start'': 0.0001, ''beta_end'': 0.02, ''beta_schedule'': ''cos_alpha'', ''input_perturbation'': 0.1, ''prediction_type'': ''epsilon'', ''eta'': 1}}'
        text_encoder: '{''type'': ''CachedFrozenOpenCLIPEmbedder'', ''params'': {''arch'': ''ViT-B-32'', ''version'': ''laion2b_s34b_b79k'', ''max_length'': 77, ''freeze'': True, ''layer'': ''penultimate'', ''enable_cache_token_limit'': True}}'
        training: '{''learning_rate'': 0.001, ''optimizer'': ''Adam'', ''loss'': ''MSELoss'', ''num_epochs'': 5, ''batch_size'': 512, ''enable_guidance_train'': True, ''guidance_train_p'': 0.1, ''cached_text_enc'': True, ''output_path'': ''./models/trained/'', ''model_name'': ''test_model'', ''experiment_name'': ''quick_test_srv_experiment'', ''ckpt_path'': ''./cp_saves'', ''ckpt_interval'': 1, ''wandb'': {''enable'': True, ''project'': ''qcircuit-generation'', ''run_name'': ''test_run''}}'
_flags_cache:
    value:
        allow_objects: null
        convert: null
        readonly: null
        struct: true
_metadata:
    value:
        element_type: typing.Any
        flags_root: false
        key: training
        key_type: typing.Any
        object_type: builtins.dict
        optional: true
        ref_type: typing.Any
_parent:
    value: '{''datasets'': {''gate_set'': [''h'', ''cx''], ''num_qubits'': 5, ''num_samples'': 100000, ''min_gates'': 4, ''max_gates'': 20, ''backbone'': ''qiskit'', ''condition_type'': ''SRV'', ''optimized'': True, ''output_path'': ''./datasets/srv_dataset'', ''device'': ''auto'', ''n_jobs'': 4}, ''evaluation'': {''dataset'': ''./datasets/srv_dataset'', ''model_dir'': ''./models/trained/default_model_srv'', ''hf_repo'': None, ''num_samples'': 64, ''model_params'': {''guidance_scale'': 10.0, ''sample_steps'': 20, ''auto_batch_size'': 512}}, ''training'': {''general'': {''output_path'': ''./models/trained/'', ''model_name'': ''test_model_srv'', ''experiment_name'': ''quick_test_srv_experiment'', ''dataset'': ''../datasets/paper_quditkit'', ''njobs'': 16, ''device'': ''auto'', ''resume'': False, ''verbose'': True}, ''model'': {''type'': ''QC_Cond_UNet'', ''save_type'': ''pt'', ''params'': {''model_features'': [128, 128, 256], ''clr_dim'': 8, ''num_clrs'': 9, ''t_emb_size'': 256, ''cond_emb_size'': 512, ''num_heads'': [8, 8, 2], ''num_res_blocks'': [2, 2, 2], ''transformer_depths'': [1, 1, 1]}}, ''training'': {''learning_rate'': 0.001, ''optimizer'': ''Adam'', ''loss'': ''MSELoss'', ''num_epochs'': 5, ''batch_size'': 512, ''enable_guidance_train'': True, ''guidance_train_p'': 0.1, ''cached_text_enc'': True, ''output_path'': ''./models/trained/'', ''model_name'': ''test_model'', ''experiment_name'': ''quick_test_srv_experiment'', ''ckpt_path'': ''./cp_saves'', ''ckpt_interval'': 1, ''wandb'': {''enable'': True, ''project'': ''qcircuit-generation'', ''run_name'': ''test_run''}}, ''text_encoder'': {''type'': ''CachedFrozenOpenCLIPEmbedder'', ''params'': {''arch'': ''ViT-B-32'', ''version'': ''laion2b_s34b_b79k'', ''max_length'': 77, ''freeze'': True, ''layer'': ''penultimate'', ''enable_cache_token_limit'': True}}, ''scheduler'': {''type'': ''DDIMScheduler'', ''params'': {''num_train_timesteps'': 1000, ''beta_start'': 0.0001, ''beta_end'': 0.02, ''beta_schedule'': ''cos_alpha'', ''input_perturbation'': 0.1, ''prediction_type'': ''epsilon'', ''eta'': 1}}}}'
_wandb:
    value:
        cli_version: 0.23.1
        e:
            6fk6rbbbaiziuoefwkpghqodci7fx118:
                args:
                    - training=quick_test_srv
                    - training.general.dataset=../datasets/paper_quditkit
                codePath: scripts/train_model.py
                codePathLocal: train_model.py
                cpu_count: 24
                cpu_count_logical: 48
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "32212254720"
                        used: "9376100352"
                email: lidungl@archimedia.at
                executable: /usr/local/bin/python
                git:
                    commit: b198ac1c19035c9e4086ac7d40159403e692d102
                    remote: https://github.com/lionlion37/qcircuit-generation.git
                gpu: NVIDIA RTX A4500
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 7168
                      memoryTotal: "21464350720"
                      name: NVIDIA RTX A4500
                      uuid: GPU-8d000595-96f1-1f83-3f4f-d0d781ca1a66
                host: cdbbc2c75ef6
                memory:
                    total: "270097338368"
                os: Linux-6.5.0-45-generic-x86_64-with-glibc2.39
                program: /workspace/qcircuit-generation/scripts/train_model.py
                python: CPython 3.12.3
                root: /workspace/qcircuit-generation/scripts
                startedAt: "2025-12-26T19:17:43.832635Z"
                writerId: 6fk6rbbbaiziuoefwkpghqodci7fx118
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 50
                - 53
                - 63
                - 105
            "2":
                - 1
                - 5
                - 41
                - 49
                - 50
                - 53
                - 63
                - 105
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.12.3
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
